services:
  postgres:
    image: postgres:16
    container_name: attendance-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: attendance_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: